# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jhcook/macos-sierra"
  config.vm.provision "file", source: "../../workstation-setup", destination: "~/workstation-setup"
  config.vm.provision :shell, privileged: false, inline: "/Users/vagrant/workstation-setup/setup.sh"
end
